### ISSUE TITLE
`cfg`s do not allow a default fall through

### ISSUE THREAD

**Issue by dlrobertson** [myfreeweb/shmemfdrs#1]
In the code this crate came from, there was a default fall through. If the target OS was not linux (with memfd enabled) or freebsd the "default" `create_shmem` was used. https://github.com/servo/ipc-channel/blob/master/src/platform/unix/mod.rs#L948-L961

**Comment by myfreeweb** [comment]
uhh it's right here https://github.com/myfreeweb/shmemfdrs/blob/10bd13c7c58a1df7fb408ba5d92922c989bfe5af/src/lib.rs#L9-L20 I have actually tested it on linux without memfd.

**Comment by dlrobertson** [comment]
ugh. you're right.... my bad

**Comment by dlrobertson** [comment]
I clearly have not had enough coffee yet :smile:

**Comment by dlrobertson** [comment]
> I have actually tested it on linux without memfd.

Ran a quick bench and test run on my box with `memfd` enabled and didn't see any failures. I also verified that it actually called memfd_create.
